FROM apache/airflow:2.2.4

USER airflow

RUN PATH=$PATH:~/.local/bin

RUN python -m pip install --upgrade pip

COPY ./scripts /opt/airflow/scripts
# install requirements
COPY ./requirements.txt /.
RUN pip install -r /requirements.txt
