---
version: '3'
services:
  memlish:
    env_file:
      - ~/memlish.env
    build:
      context: .
      dockerfile: ./Dockerfile.cuda
    restart: unless-stopped
    container_name: memlish

    logging:
      driver: "fluentd"
      options:
        fluentd-address: ec2-34-245-85-126.eu-west-1.compute.amazonaws.com:7030
        tag: memlish.bot

    ports:
      - "7654:7654"
    volumes:
      - "./:/app"
      - "./infrastructure/nginx/certs/:/certs/"

    working_dir: /app

    command: >
      gunicorn apps.bot.main:my_web_app --workers 1 --bind 0.0.0.0:7654 --worker-class aiohttp.GunicornWebWorker

  nginx: 
    image: nginx:latest
    env_file:
      - ~/memlish.env
    environment:
      - BOT_CONTAINER_NAME=memlish
      - BOT_CONTAINER_PORT=7654
    logging:
      driver: none
    container_name: production_nginx
    volumes:
      - ./infrastructure/nginx/conf.d/:/nginx_confs/
      - ./infrastructure/nginx/certs/:/certs/
      - ~/data/imgflip/:/public/static_memes/
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "envsubst < /nginx_confs/nginx.conf > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
