---
version: '3.3'
services:
  memlish-jina-search-server:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ec2-3-251-68-86.eu-west-1.compute.amazonaws.com:7030
        tag: memlish.server
    mem_limit: 18g
    env_file: 
      - ~/memlish.env
    build:
      context: .
      dockerfile: ./Dockerfile.cuda
    restart: unless-stopped
    container_name: memlish-jina-search-server
    ports:
      - "0.0.0.0:${JINA_FLOW_PORT}:${JINA_FLOW_PORT}"
    volumes:
      - "./:/app"
      - "~/data:/data"

    working_dir: /app
    
    command: >
      python /app/apps/jina.server/main.py --port ${JINA_FLOW_PORT}
