---
version: '3.3'
services:
  memlish-jina-search-server:
    mem_limit: 18g
    env_file: 
      - /home/cont/memlish.env
    runtime: nvidia
    build:
      context: .
      dockerfile: ./Dockerfile.cuda
    restart: unless-stopped
    container_name: memlish-jina-search-server
    ports:
      - "0.0.0.0:${JINA_FLOW_PORT}:${JINA_FLOW_PORT}"
    volumes:
      - "./:/app"
      - "~/data:/data"

    working_dir: /app
    
    command: >
      python /app/apps/jina.server/main.py --port ${JINA_FLOW_PORT}
