---
version: "3.3"
services:
  memlish-mongodb:
    image : mongo:4.0.28
    env_file:
        /home/ubuntu/memlish.env
    volumes:
        - /home/ubuntu/data/mongodb_data:/data/db
    ports:
        - 7543:27017
        - 8081:8081
    restart: unless-stopped
    container_name: memlish-mongodb
